In [1]:
from utils import *
import numpy as np
import torch.optim as optim
import ray
from ray import tune

utils.py loaded


## Learning y and var

In [5]:
output_2_fvc = model_run(file_name = 'FVC', num_epochs= 500, hidden_sizes =  [50,10], output_size = 2)

Epoch [1/500], Train Loss: 5.0578, Val Loss: 5.2345
Epoch [100/500], Train Loss: -0.2741, Val Loss: 70.3601
Epoch [200/500], Train Loss: -0.5554, Val Loss: 986.8797
Epoch [300/500], Train Loss: -0.9224, Val Loss: 16724.0332
Epoch [400/500], Train Loss: -0.6181, Val Loss: 74.5441
Epoch [500/500], Train Loss: -0.8872, Val Loss: 1469.0956
val loss at Epoch :  49
MAPE val:  4.192838668823242
MSE val:  0.03468561917543411
Loss tfp val:  0.20116481184959412
MAPE test:  6.219310760498047
MSE test:  0.04740426689386368
Loss tfp test:  0.5905280709266663


In [6]:
output_2_fvc 

(tensor([[2.8091],
         [3.0718],
         [3.2758],
         [3.2628],
         [3.1932]]),
 tensor([[-1.2952],
         [-1.4084],
         [-1.5517],
         [-1.5378],
         [-1.4968]]))

In [20]:
output_2_fev1 = model_run(file_name = 'FEV1', num_epochs= 500, hidden_sizes =  [50,10], output_size = 2)

Epoch [1/500], Train Loss: 4.2035, Val Loss: 3.5175
Epoch [100/500], Train Loss: 0.4302, Val Loss: 0.4227
Epoch [200/500], Train Loss: 1.2654, Val Loss: 0.8331
Epoch [300/500], Train Loss: -0.4932, Val Loss: 0.0698
Epoch [400/500], Train Loss: 1.1664, Val Loss: 0.9314
Epoch [500/500], Train Loss: 0.0824, Val Loss: 0.2650
val loss at Epoch :  189
MAPE val:  3.433788537979126
MSE val:  0.019140856340527534
Loss tfp val:  -0.6632509231567383
MAPE test:  10.863091468811035
MSE test:  0.12362875044345856
Loss tfp test:  17.428630828857422


In [6]:
output_2_fev1

(tensor([[2.6744],
         [1.9241],
         [3.0492],
         [3.4553],
         [2.7051]]),
 tensor([[-4.2114],
         [-3.0975],
         [-4.1102],
         [-4.8354],
         [-2.3073]]))

## Learning y

In [7]:
output_1_fvc = model_run(file_name = 'FVC', num_epochs= 500, hidden_sizes =  [50,10], output_size = 1)

Epoch [1/500], Train Loss: 10.2448, Val Loss: 11.1006
Epoch [100/500], Train Loss: 0.0622, Val Loss: 0.0490
Epoch [200/500], Train Loss: 0.0489, Val Loss: 0.0920
Epoch [300/500], Train Loss: 0.0441, Val Loss: 0.0877
Epoch [400/500], Train Loss: 0.0414, Val Loss: 0.0790
Epoch [500/500], Train Loss: 0.0396, Val Loss: 0.0704
val loss at Epoch :  66
MAPE val:  3.0852341651916504
MSE val:  0.01854533888399601
MAPE test:  8.039169311523438
MSE test:  0.06806212663650513


In [8]:
output_1_fvc

tensor([[2.8411],
        [3.1889],
        [3.3528],
        [3.4241],
        [3.2285]])

In [9]:
output_1_fev1 = model_run(file_name = 'FEV1', num_epochs= 500, hidden_sizes =  [50,10], output_size = 1)

Epoch [1/500], Train Loss: 10.9925, Val Loss: 9.5414
Epoch [100/500], Train Loss: 0.0820, Val Loss: 0.1371
Epoch [200/500], Train Loss: 0.0274, Val Loss: 0.8322
Epoch [300/500], Train Loss: 0.0202, Val Loss: 0.7312
Epoch [400/500], Train Loss: 0.0155, Val Loss: 0.5251
Epoch [500/500], Train Loss: 0.0088, Val Loss: 0.5968
val loss at Epoch :  43
MAPE val:  4.456958770751953
MSE val:  0.02602154016494751
MAPE test:  9.542654991149902
MSE test:  0.11077382415533066


In [10]:
output_1_fev1

tensor([[2.6744],
        [2.0870],
        [3.1219],
        [3.2695],
        [2.8194]])

### Hyper parameter tuning

In [ ]:
config = {
    "hidden_size": tune.choice([[50,10] ,[60,30,5], [75,35,15,5],[128,80,50,30,16]]),
    'lr':tune.choice([0.01, 0.001]),
    "num_epochs": tune.choice([2000])
}

In [11]:
best_config_fvc_out2 = {'hidden_size': [75, 35, 15, 5], 'lr': 0.001, 'num_epochs': 2000}
best_config_fev1_out2 = {'hidden_size': [75, 35, 15, 5], 'lr': 0.01, 'num_epochs': 2000}
best_config_fvc_out1 = {'hidden_size': [60, 30, 5], 'lr': 0.01, 'num_epochs': 2000}        
best_config_fev1_out1 = {'hidden_size': [128, 80, 50, 30, 16], 'lr': 0.001, 'num_epochs': 2000}

In [12]:
output_2_fvc = model_run(file_name = 'FVC', num_epochs= best_config_fvc_out2['num_epochs'], hidden_sizes =  best_config_fvc_out2['hidden_size'], output_size = 2, lr = best_config_fvc_out2['lr'])

Epoch [1/2000], Train Loss: 6.0961, Val Loss: 6.7044
Epoch [100/2000], Train Loss: 2.1513, Val Loss: 2.4245
Epoch [200/2000], Train Loss: 1.3433, Val Loss: 1.3674
Epoch [300/2000], Train Loss: 0.7230, Val Loss: 0.7421
Epoch [400/2000], Train Loss: -0.1157, Val Loss: 3.7265
Epoch [500/2000], Train Loss: -0.2032, Val Loss: 5.3934
Epoch [600/2000], Train Loss: -0.2553, Val Loss: 8.0654
Epoch [700/2000], Train Loss: -0.3398, Val Loss: 14.3098
Epoch [800/2000], Train Loss: -0.4875, Val Loss: 92.6303
Epoch [900/2000], Train Loss: -0.6391, Val Loss: 815.2264
Epoch [1000/2000], Train Loss: -0.7994, Val Loss: 6770.7720
Epoch [1100/2000], Train Loss: -0.9263, Val Loss: 13821.8809
Epoch [1200/2000], Train Loss: -1.0524, Val Loss: 24083.0977
Epoch [1300/2000], Train Loss: -1.2094, Val Loss: 52720.2109
Epoch [1400/2000], Train Loss: -1.2855, Val Loss: 48187.1641
Epoch [1500/2000], Train Loss: -1.5151, Val Loss: 110016.9844
Epoch [1600/2000], Train Loss: -1.6239, Val Loss: 108894.8516
Epoch [1700/20

In [13]:
output_2_fev1 = model_run(file_name = 'FEV1', num_epochs= best_config_fev1_out2['num_epochs'], hidden_sizes =  best_config_fev1_out2['hidden_size'], output_size = 2, lr = best_config_fev1_out2['lr'])

Epoch [1/2000], Train Loss: 5.9789, Val Loss: 5.9104
Epoch [100/2000], Train Loss: 1.4132, Val Loss: 1.4002
Epoch [200/2000], Train Loss: 4.3549, Val Loss: 4.4995
Epoch [300/2000], Train Loss: -0.3326, Val Loss: 0.6809
Epoch [400/2000], Train Loss: -0.2092, Val Loss: 0.3909
Epoch [500/2000], Train Loss: -0.3758, Val Loss: -0.0530
Epoch [600/2000], Train Loss: 1.1036, Val Loss: 6.4166
Epoch [700/2000], Train Loss: 0.9856, Val Loss: 1.6015
Epoch [800/2000], Train Loss: -0.5159, Val Loss: 0.0710
Epoch [900/2000], Train Loss: -1.1755, Val Loss: 3.2250
Epoch [1000/2000], Train Loss: -0.5053, Val Loss: 1.0358
Epoch [1100/2000], Train Loss: -1.1795, Val Loss: 66.8696
Epoch [1200/2000], Train Loss: -1.2377, Val Loss: 194.0685
Epoch [1300/2000], Train Loss: 5.9887, Val Loss: 3.6114
Epoch [1400/2000], Train Loss: -1.0216, Val Loss: 5.6423
Epoch [1500/2000], Train Loss: -0.2138, Val Loss: 0.1450
Epoch [1600/2000], Train Loss: -0.6145, Val Loss: 0.6199
Epoch [1700/2000], Train Loss: -0.8178, Val L

In [18]:
output_1_fvc = model_run(file_name = 'FVC', num_epochs= best_config_fvc_out1['num_epochs'], hidden_sizes =  best_config_fvc_out1['hidden_size'], output_size = 1, lr = best_config_fvc_out1['lr'])

Epoch [1/2000], Train Loss: 8.7189, Val Loss: 9.3833
Epoch [100/2000], Train Loss: 0.0557, Val Loss: 0.0428
Epoch [200/2000], Train Loss: 0.0441, Val Loss: 0.0553
Epoch [300/2000], Train Loss: 0.0400, Val Loss: 0.0629
Epoch [400/2000], Train Loss: 0.0379, Val Loss: 0.0702
Epoch [500/2000], Train Loss: 0.0363, Val Loss: 0.0838
Epoch [600/2000], Train Loss: 0.0349, Val Loss: 0.1008
Epoch [700/2000], Train Loss: 0.0332, Val Loss: 0.1195
Epoch [800/2000], Train Loss: 0.0313, Val Loss: 0.1472
Epoch [900/2000], Train Loss: 0.0292, Val Loss: 0.1897
Epoch [1000/2000], Train Loss: 0.0271, Val Loss: 0.1984
Epoch [1100/2000], Train Loss: 0.0176, Val Loss: 0.0310
Epoch [1200/2000], Train Loss: 0.0097, Val Loss: 0.0356
Epoch [1300/2000], Train Loss: 0.0077, Val Loss: 0.0551
Epoch [1400/2000], Train Loss: 0.0073, Val Loss: 0.0474
Epoch [1500/2000], Train Loss: 0.0047, Val Loss: 0.0466
Epoch [1600/2000], Train Loss: 0.0039, Val Loss: 0.0325
Epoch [1700/2000], Train Loss: 0.0035, Val Loss: 0.0783
Epoc

In [25]:
output_1_fev1 = model_run(file_name = 'FEV1', num_epochs= best_config_fev1_out1['num_epochs'], hidden_sizes =  best_config_fev1_out1['hidden_size'], output_size = 1, lr = best_config_fev1_out1['lr'])

Epoch [1/2000], Train Loss: 9.2454, Val Loss: 9.6518
Epoch [100/2000], Train Loss: 0.1130, Val Loss: 0.1092
Epoch [200/2000], Train Loss: 0.0477, Val Loss: 0.1248
Epoch [300/2000], Train Loss: 0.0182, Val Loss: 0.2493
Epoch [400/2000], Train Loss: 0.0069, Val Loss: 0.3521
Epoch [500/2000], Train Loss: 0.0025, Val Loss: 0.3821
Epoch [600/2000], Train Loss: 0.0007, Val Loss: 0.3603
Epoch [700/2000], Train Loss: 0.0002, Val Loss: 0.3140
Epoch [800/2000], Train Loss: 0.0001, Val Loss: 0.3126
Epoch [900/2000], Train Loss: 0.0001, Val Loss: 0.3043
Epoch [1000/2000], Train Loss: 0.0001, Val Loss: 0.3354
Epoch [1100/2000], Train Loss: 0.0001, Val Loss: 0.3497
Epoch [1200/2000], Train Loss: 0.0000, Val Loss: 0.3385
Epoch [1300/2000], Train Loss: 0.0002, Val Loss: 0.3728
Epoch [1400/2000], Train Loss: 0.0000, Val Loss: 0.3502
Epoch [1500/2000], Train Loss: 0.0000, Val Loss: 0.3666
Epoch [1600/2000], Train Loss: 0.0000, Val Loss: 0.3622
Epoch [1700/2000], Train Loss: 0.0000, Val Loss: 0.2783
Epoc

Summary 


In [ ]:
# fvc output 2
# MAPE test:  5.872068405151367
# tune:
# MAPE test:  5.188878536224365


# fev1 output 2
# MAPE test:  10.863091468811035
# tune :
# MAPE test:  10.298738479614258


# fvc output 1
# MAPE test:  8.039169311523438
# tune:
# MAPE test:  5.899529457092285


# fev1 output 1
# MAPE test:  9.542654991149902
# tune:
# MAPE test:  9.465457916259766

In [2]:
analysis_fvc_out1 = raytune_fun(output_size = 1, file_name='FVC') 

TuneError: ('Trials did not complete', [train_mlp_102d9_00000, train_mlp_102d9_00001, train_mlp_102d9_00002, train_mlp_102d9_00003, train_mlp_102d9_00004, train_mlp_102d9_00005, train_mlp_102d9_00006, train_mlp_102d9_00007, train_mlp_102d9_00008, train_mlp_102d9_00009])

In [ ]:
best_config_fvc = analysis_fvc_out1.get_best_config(metric="val_loss", mode="min")
print("Best config:", best_config_fvc)

In [4]:
ray.shutdown()
ray.init()
analysis_fvc = tune.run( train_mlp_output_1,
            config=config,
            num_samples=10,
            progress_reporter=tune.CLIReporter()
        ) 

2023-05-03 23:32:32,985	INFO tune.py:945 -- Total run time: 119.70 seconds (119.46 seconds for the tuning loop).


== Status ==
Current time: 2023-05-03 23:32:32 (running for 00:01:59.55)
Using FIFO scheduling algorithm.
Logical resource usage: 0/8 CPUs, 0/1 GPUs
Result logdir: C:\Users\HP\ray_results\train_mlp_output_1_2023-05-03_23-30-33
Number of trials: 10/10 (10 TERMINATED)
+--------------------------------+------------+-----------------+-----------------+--------+--------+------------------+------------+
| Trial name                     | status     | loc             | hidden_size     |     lr |   iter |   total time (s) |   val_loss |
|--------------------------------+------------+-----------------+-----------------+--------+--------+------------------+------------|
| train_mlp_output_1_6614e_00000 | TERMINATED | 127.0.0.1:21600 | [75, 35, 15, 5] | 0.01   |      1 |        0.512657  |    11.1893 |
| train_mlp_output_1_6614e_00001 | TERMINATED | 127.0.0.1:14260 | [75, 35, 15, 5] | 0.01   |      1 |        0.0180161 |    11.1893 |
| train_mlp_output_1_6614e_00002 | TERMINATED | 127.0.0.1:1924 

In [6]:
best_config_fvc = analysis_fvc.get_best_config(metric="val_loss", mode="min")
print("Best config:", best_config_fvc)

Best config: {'hidden_size': [60, 30, 5], 'lr': 0.01}
