In [1]:
from utils import * 

utils.py loaded


## Learning y and var

In [2]:
output_2_fvc = model_run(file_name = 'FVC', num_epochs= 500, hidden_sizes =  [50,10], output_size = 2)

Epoch [1/500], Train Loss: 4.8063, Val Loss: 3.9391
Epoch [100/500], Train Loss: -0.2833, Val Loss: 15.1438
Epoch [200/500], Train Loss: -0.6941, Val Loss: 0.1997
Epoch [300/500], Train Loss: -0.5084, Val Loss: -0.1482
Epoch [400/500], Train Loss: -1.0380, Val Loss: 2.8335
Epoch [500/500], Train Loss: -1.6059, Val Loss: 8.3274
MAPE test:  5.822160339355468


In [3]:
output_2_fvc 

(tensor([[3.1577],
         [3.0649],
         [3.0660],
         [3.5160],
         [3.3191]], grad_fn=<ReshapeAliasBackward0>),
 tensor([[0.0206],
         [0.0260],
         [0.0344],
         [0.0166],
         [0.0212]], grad_fn=<ExpBackward0>))

In [4]:
output_2_fvc = model_run(file_name = 'FVC', num_epochs= 500, hidden_sizes =  [50,10], output_size = 1, type_run = 'without_dataloader')

Epoch [1/500], Train Loss: 9.7188, Val Loss: 10.3862
Epoch [100/500], Train Loss: 0.0602, Val Loss: 0.0755
Epoch [200/500], Train Loss: 0.0487, Val Loss: 0.0833
Epoch [300/500], Train Loss: 0.0437, Val Loss: 0.0716
Epoch [400/500], Train Loss: 0.0409, Val Loss: 0.0622
Epoch [500/500], Train Loss: 0.0390, Val Loss: 0.0571
val loss at Epoch :  57
MAPE val:  2.8673808574676514
MSE val:  0.0171546321362257
MAPE test:  7.880953788757324
MSE test:  0.06490512192249298


In [5]:
print(output_2_fvc)

tensor([[2.8908],
        [3.2092],
        [3.3516],
        [3.4172],
        [3.2406]])


In [6]:
output_2_fev1 = model_run(file_name = 'FEV1', num_epochs= 500, hidden_sizes =  [50,10], output_size = 2)

Epoch [1/500], Train Loss: 3.6416, Val Loss: 2.8251
Epoch [100/500], Train Loss: -0.0989, Val Loss: 0.1270
Epoch [200/500], Train Loss: -0.2612, Val Loss: 0.0592
Epoch [300/500], Train Loss: -0.3856, Val Loss: 0.0711
Epoch [400/500], Train Loss: -0.1991, Val Loss: -0.0319
Epoch [500/500], Train Loss: -0.1635, Val Loss: 0.3311
MAPE test:  8.743933010101319


In [7]:
output_2_fev1

(tensor([[2.6659],
         [2.7566],
         [3.1802],
         [3.3837],
         [3.2814]], grad_fn=<ReshapeAliasBackward0>),
 tensor([[0.0691],
         [0.0550],
         [0.0106],
         [0.0042],
         [0.0175]], grad_fn=<ExpBackward0>))

## Learning y

In [18]:
output_1_fvc = model_run(file_name = 'FVC', num_epochs= 500, hidden_sizes =  [50,10], output_size = 1)

Epoch [1/500], Train Loss: 8.3993, Val Loss: 6.4152
Epoch [100/500], Train Loss: 0.0608, Val Loss: 0.1169
Epoch [200/500], Train Loss: 0.0456, Val Loss: 0.0713
Epoch [300/500], Train Loss: 0.0639, Val Loss: 0.1187
Epoch [400/500], Train Loss: 0.0296, Val Loss: 0.0501
Epoch [500/500], Train Loss: 0.0121, Val Loss: 0.0578
MAPE test:  7.843387603759766


In [19]:
output_1_fvc

tensor([[2.8671],
        [3.2058],
        [3.3606],
        [3.3911],
        [3.2314]], grad_fn=<ReshapeAliasBackward0>)

In [20]:
output_1_fev1 = model_run(file_name = 'FEV1', num_epochs= 500, hidden_sizes =  [50,10], output_size = 1)

Epoch [1/500], Train Loss: 5.1707, Val Loss: 3.9330
Epoch [100/500], Train Loss: 0.0143, Val Loss: 0.0693
Epoch [200/500], Train Loss: 0.0115, Val Loss: 0.1103
Epoch [300/500], Train Loss: 0.0049, Val Loss: 0.1963
Epoch [400/500], Train Loss: 0.0038, Val Loss: 0.1802
Epoch [500/500], Train Loss: 0.0031, Val Loss: 0.1809
MAPE test:  7.96909236907959


In [21]:
output_1_fev1

tensor([[2.6579],
        [2.4321],
        [3.0536],
        [3.3141],
        [3.1089]], grad_fn=<ReshapeAliasBackward0>)

### Hyper parameter tuning

In [22]:
config = {
    "hidden_size": tune.choice([[50,10] ,[60,30,5], [75,35,15,5],[128,80,50,30,16]]),
    'lr':tune.choice([0.01, 0.001]),
    "num_epochs": tune.choice([2000])
}

In [23]:
best_config_fvc_out2 = {'hidden_size': [75, 35, 15, 5], 'lr': 0.001, 'num_epochs': 500}
best_config_fev1_out2 = {'hidden_size': [75, 35, 15, 5], 'lr': 0.01, 'num_epochs': 500}
best_config_fvc_out1 = {'hidden_size': [60, 30, 5], 'lr': 0.01, 'num_epochs': 500}        
best_config_fev1_out1 = {'hidden_size': [128, 80, 50, 30, 16], 'lr': 0.001, 'num_epochs': 500}

In [24]:
output_2_fvc = model_run(file_name = 'FVC', num_epochs= best_config_fvc_out2['num_epochs'], hidden_sizes =  best_config_fvc_out2['hidden_size'], output_size = 2, lr = best_config_fvc_out2['lr'])

Epoch [1/500], Train Loss: 7.5943, Val Loss: 8.1030
Epoch [100/500], Train Loss: -0.0895, Val Loss: 4.3815
Epoch [200/500], Train Loss: -0.1199, Val Loss: 6.2287
Epoch [300/500], Train Loss: -0.1957, Val Loss: 8.5090
Epoch [400/500], Train Loss: -0.1763, Val Loss: 15.6482
Epoch [500/500], Train Loss: -0.2335, Val Loss: 14.4548
MAPE test:  7.058881950378418


In [25]:
output_2_fev1 = model_run(file_name = 'FEV1', num_epochs= best_config_fev1_out2['num_epochs'], hidden_sizes =  best_config_fev1_out2['hidden_size'], output_size = 2, lr = best_config_fev1_out2['lr'])

Epoch [1/500], Train Loss: 4.1476, Val Loss: 2.6850
Epoch [100/500], Train Loss: 0.0832, Val Loss: 0.2637
Epoch [200/500], Train Loss: 0.0672, Val Loss: 0.1609
Epoch [300/500], Train Loss: -0.0993, Val Loss: 0.2762
Epoch [400/500], Train Loss: -0.2233, Val Loss: 0.6341
Epoch [500/500], Train Loss: -0.2244, Val Loss: 0.3012
MAPE test:  6.837859439849853


In [26]:
output_1_fvc = model_run(file_name = 'FVC', num_epochs= best_config_fvc_out1['num_epochs'], hidden_sizes =  best_config_fvc_out1['hidden_size'], output_size = 1, lr = best_config_fvc_out1['lr'])

Epoch [1/500], Train Loss: 8.1137, Val Loss: 5.2728
Epoch [100/500], Train Loss: 0.0467, Val Loss: 0.0939
Epoch [200/500], Train Loss: 0.0421, Val Loss: 0.0812
Epoch [300/500], Train Loss: 0.0398, Val Loss: 0.1245
Epoch [400/500], Train Loss: 0.0341, Val Loss: 0.1738
Epoch [500/500], Train Loss: 0.0169, Val Loss: 0.0595
MAPE test:  8.42601375579834


In [27]:
output_1_fev1 = model_run(file_name = 'FEV1', num_epochs= best_config_fev1_out1['num_epochs'], hidden_sizes =  best_config_fev1_out1['hidden_size'], output_size = 1, lr = best_config_fev1_out1['lr'])

Epoch [1/500], Train Loss: 7.6587, Val Loss: 7.7153
Epoch [100/500], Train Loss: 0.0245, Val Loss: 0.0559
Epoch [200/500], Train Loss: 0.0109, Val Loss: 0.0787
Epoch [300/500], Train Loss: 0.0098, Val Loss: 0.0836
Epoch [400/500], Train Loss: 0.0083, Val Loss: 0.1129
Epoch [500/500], Train Loss: 0.0032, Val Loss: 0.1093
MAPE test:  9.896806907653808


Summary 


In [ ]:
# fvc output 2
# MAPE test:  5.872068405151367
# tune:
# MAPE test:  5.188878536224365


# fev1 output 2
# MAPE test:  10.863091468811035
# tune :
# MAPE test:  10.298738479614258


# fvc output 1
# MAPE test:  8.039169311523438
# tune:
# MAPE test:  5.899529457092285


# fev1 output 1
# MAPE test:  9.542654991149902
# tune:
# MAPE test:  9.465457916259766

In [2]:
analysis_fvc_out1 = raytune_fun(output_size = 1, file_name='FVC') 

TuneError: ('Trials did not complete', [train_mlp_102d9_00000, train_mlp_102d9_00001, train_mlp_102d9_00002, train_mlp_102d9_00003, train_mlp_102d9_00004, train_mlp_102d9_00005, train_mlp_102d9_00006, train_mlp_102d9_00007, train_mlp_102d9_00008, train_mlp_102d9_00009])

In [ ]:
best_config_fvc = analysis_fvc_out1.get_best_config(metric="val_loss", mode="min")
print("Best config:", best_config_fvc)

In [4]:
ray.shutdown()
ray.init()
analysis_fvc = tune.run( train_mlp_output_1,
            config=config,
            num_samples=10,
            progress_reporter=tune.CLIReporter()
        ) 

2023-05-03 23:32:32,985	INFO tune.py:945 -- Total run time: 119.70 seconds (119.46 seconds for the tuning loop).


== Status ==
Current time: 2023-05-03 23:32:32 (running for 00:01:59.55)
Using FIFO scheduling algorithm.
Logical resource usage: 0/8 CPUs, 0/1 GPUs
Result logdir: C:\Users\HP\ray_results\train_mlp_output_1_2023-05-03_23-30-33
Number of trials: 10/10 (10 TERMINATED)
+--------------------------------+------------+-----------------+-----------------+--------+--------+------------------+------------+
| Trial name                     | status     | loc             | hidden_size     |     lr |   iter |   total time (s) |   val_loss |
|--------------------------------+------------+-----------------+-----------------+--------+--------+------------------+------------|
| train_mlp_output_1_6614e_00000 | TERMINATED | 127.0.0.1:21600 | [75, 35, 15, 5] | 0.01   |      1 |        0.512657  |    11.1893 |
| train_mlp_output_1_6614e_00001 | TERMINATED | 127.0.0.1:14260 | [75, 35, 15, 5] | 0.01   |      1 |        0.0180161 |    11.1893 |
| train_mlp_output_1_6614e_00002 | TERMINATED | 127.0.0.1:1924 

In [6]:
best_config_fvc = analysis_fvc.get_best_config(metric="val_loss", mode="min")
print("Best config:", best_config_fvc)

Best config: {'hidden_size': [60, 30, 5], 'lr': 0.01}


In [28]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge

from sklearn.model_selection import GridSearchCV

from sklearn.model_selection import LeaveOneOut
import warnings
warnings.filterwarnings("ignore")

In [29]:
#load data correspoding to PEF, FEV1, FVC
X = np.load('Spiro_Mask_dataset/FVC_FEATURES_60.npy')
Y = np.load('Spiro_Mask_dataset/FVC_LABELS_60.npy')

In [32]:
all_set = np.delete(X,[23,55,4,9,52,44,45,33,43,20,1,50], axis=0) 
all_labels = np.delete(Y,[23,55,4,9,52,44,45,33,43,20,1,50], axis=0)

In [33]:
#LOOCV ONLY
#All left out samples
loo = LeaveOneOut()

#store the predictions here
FVC_predictions = []


regressor = RandomForestRegressor(n_jobs=-1, bootstrap=True, criterion='mae', 
                                  n_estimators=100,  max_features='auto', max_depth=300,  
                                  min_samples_leaf=1,min_samples_split=5,random_state=42)

# Create a based model
mpeList = []
for train_index, test_index in loo.split(all_set):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = all_set[train_index], all_set[test_index]
    y_train, y_test = all_labels[train_index], all_labels[test_index]

    

    #for RF and SVR
    reg = regressor.fit(X_train, y_train)
    pred = reg.predict(X_test)
    
    FVC_predictions.append(pred[0])
    
   
    
    #print("True FVC = {}, Predicted FVC = {}".format(y_test,pred))
    mpe = 100*np.mean(np.abs((y_test.reshape(-1) -pred)/y_test.reshape(-1)))
    mpeList.append(mpe)
    #print("Error on Participant ID {} is {:2f}".format(test_index,mpe))
    #print("\n")
print("Overall MPE is = {}".format(np.mean(mpeList)))
#print("Bootstrap = {},Depth = {}, Features = {}, Leaf = {}, Split = {}, Estimator = {}".format(bootstrap,depth,features,leaf,split,estimator))

FVC_predictions = np.array(FVC_predictions)

Overall MPE is = 6.048729090522371


In [79]:
from xgboost import XGBRegressor
# from sklearn.ensemble import XGBRegressor

loo = LeaveOneOut()

# Store the predictions here
FVC_predictions = []

# Instantiate the regressor
regressor = XGBRegressor(n_jobs=-1, objective='reg:squarederror', random_state=42)

# Create a list to store the mean absolute percentage error (MAPE)
mape_list = []

for train_index, test_index in loo.split(all_set):
    X_train, X_test = all_set[train_index], all_set[test_index]
    y_train, y_test = all_labels[train_index], all_labels[test_index]

    # Fit the XGBoost model
    reg = regressor.fit(X_train, y_train)
    
    # Make predictions on the left-out sample
    pred = reg.predict(X_test)
    
    FVC_predictions.append(pred[0])

    # Calculate the mean absolute percentage error (MAPE)
    mape = 100 * np.mean(np.abs((y_test.reshape(-1) - pred) / y_test.reshape(-1)))
    mape_list.append(mape)

# Calculate the overall mean MAPE
overall_mape = np.mean(mape_list)
print("Overall MAPE is =", overall_mape)

# Convert FVC_predictions to a numpy array
FVC_predictions = np.array(FVC_predictions)

Overall MAPE is = 6.772241273401555


In [81]:
mape_list

[1.1280059814453125,
 5.317711069228796,
 4.039182534088961,
 0.6196285116261466,
 4.346701027690505,
 1.7515261967976863,
 15.763404634263784,
 7.55563551379788,
 11.63446729983425,
 0.05322294664217509,
 9.532654285430903,
 15.366975691140775,
 3.018192338794933,
 1.585559013105257,
 1.288686960171427,
 2.712267484420382,
 6.403219933603323,
 1.8887930278536684,
 21.220452955153107,
 4.654681298040572,
 0.46853261278165154,
 0.00769144449478199,
 15.741674783753181,
 7.075235609374293,
 20.983485934100568,
 0.33367012120500844,
 5.099932352701822,
 2.8466869044948244,
 26.82919187365838,
 18.57961101352044,
 2.507450024990209,
 0.23117853125288437,
 5.04556713682232,
 25.598946943977808,
 2.0692673740008014,
 3.876606061144278,
 5.2677976356825305,
 5.468972640879007,
 15.08385924731983,
 3.6811694246796756,
 8.149854587935085,
 0.26177565256754554,
 2.826091484241543,
 3.0244695412001006,
 8.974993298625385,
 3.8660317136530273,
 8.709634434093124,
 2.5772340369946978]

In [80]:
FVC_predictions

array([3.0338402, 3.560054 , 3.0795598, 3.2097661, 3.3000388, 3.663055 ,
       3.0325174, 3.3342247, 3.226236 , 2.8915381, 3.505045 , 3.2922246,
       3.113116 , 3.2608964, 3.160207 , 3.2046227, 3.2559385, 3.1003141,
       3.236586 , 3.2442951, 3.0058503, 3.12024  , 2.763673 , 3.2151968,
       3.8230782, 3.149456 , 3.152998 , 3.4247947, 3.1024423, 3.4522245,
       3.3049974, 3.382163 , 3.1334963, 3.7930882, 3.0824919, 3.2305624,
       3.2738285, 2.868756 , 3.130281 , 3.017122 , 3.1471608, 2.9921467,
       3.0221086, 3.015939 , 3.1130552, 3.2877817, 3.012582 , 3.2149513],
      dtype=float32)

In [82]:
len(FVC_predictions)

48

In [78]:
from sklearn.svm import SVR
loo = LeaveOneOut()

# Store the predictions here
FVC_predictions = []
# Instantiate the SVR model
# regressor = SVR(kernel='rbf', C=1.0, epsilon=0.1)
regressor = SVR(kernel='rbf', C=10, gamma=10, epsilon=.1)
# Create a list to store the mean absolute percentage error (MAPE)
mape_list = []

for train_index, test_index in loo.split(all_set):
    X_train, X_test = all_set[train_index], all_set[test_index]
    y_train, y_test = all_labels[train_index], all_labels[test_index]

    # Fit the SVR model
    reg = regressor.fit(X_train, y_train)
    
    # Make predictions on the left-out sample
    pred = reg.predict(X_test)
    
    FVC_predictions.append(pred[0])

    # Calculate the mean absolute percentage error (MAPE)
    mape = 100 * np.mean(np.abs((y_test.reshape(-1) - pred) / y_test.reshape(-1)))
    mape_list.append(mape)

# Calculate the overall mean MAPE
overall_mape = np.mean(mape_list)
print("Overall MAPE is =", overall_mape)

# Convert FVC_predictions to a numpy array
FVC_predictions = np.array(FVC_predictions)


Overall MAPE is = 6.613657490460166


In [6]:
import torch

In [7]:
random_seed = 1
torch.manual_seed(random_seed)
print(torch.rand(1,3))

print(torch.rand(1,3))

tensor([[0.7576, 0.2793, 0.4031]])
tensor([[0.7347, 0.0293, 0.7999]])


In [58]:
random_seed = 1
torch.manual_seed(random_seed)
print(torch.rand(1,3))
torch.manual_seed(random_seed)
print(torch.rand(1,3))

tensor([[0.7576, 0.2793, 0.4031]])
tensor([[0.7576, 0.2793, 0.4031]])


In [47]:
torch.rand(1,3)

tensor([[0.4550, 0.5725, 0.4980]])

In [51]:
torch.manual_seed(random_seed)
torch.rand(1,3)

tensor([[0.7576, 0.2793, 0.4031]])

In [40]:
from sklearn.model_selection import LeaveOneOut, KFold
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
# from sklearn.metrics import mean_squared_error,mean_absolute_error
import pandas as pd
import numpy as np

# Loading npy data.
X = np.load("Spiro_Mask_dataset/FEV1_FEATURES_60.npy")
y = np.load("Spiro_Mask_dataset/FEV1_LABELS_60.npy")

X= pd.DataFrame(np.delete(X,[23,55,4,9,52,44,45,33,43,20,1,50],axis=0))
y= pd.DataFrame(np.delete(y,[23,55,4,9,52,44,45,33,43,20,1,50],axis=0))

# Instantiating Random forrest Regressor.
RF = RandomForestRegressor( n_jobs=-1, bootstrap=True, criterion='mae', 
                                  n_estimators=500,  max_features=1.0, max_depth=300,  
                                  min_samples_leaf=1, min_samples_split=5 ,random_state=42)

# Instantiating Decision Tree Regressor.
DT = DecisionTreeRegressor( criterion='absolute_error',min_samples_leaf=1, 
                                min_samples_split=5 ,random_state=42)

# Instantiating Linear Regressor.
LR = LinearRegression()

# Estimator/Regressor Dictionary.
RegDict = { "Random_Forrest_Regression" :   RF,
            "Decision_Tree_Regression" :    DT,
            "Linear_Regression":            LR }

tot = len(X)
# Instantiating Leave_One_Out split function.
loo = LeaveOneOut()

def MAPE_func(y_true,y_pred):
    abserr = np.zeros(len(y_true))
    for i in range(len(y_true)):
        abserr[i] = np.abs( (y_true[i] - y_pred[i]) / y_true[i])
    return 100 * np.mean(abserr)


# We run for every Regressor.
for Reg in RegDict:

    print("For : ",Reg)
    Model = RegDict[Reg]
    prog = 0
    y_GT = []
    y_PT = []
    abserror=[]

    # For every split obtained by Leave_One_Out split function.
    for i,(train_index, test_index) in enumerate(loo.split(X)):



        #m To show some sort of progress.
        prog = prog + 1
        print("Progress : {0}/{1}\r".format(prog,tot),end=" ")

        # Test-train split for the fold.
        X_Train, X_Test = X.iloc[train_index],X.iloc[test_index]
        y_Train, y_Test = y.iloc[train_index],y.iloc[test_index]
        
        Model.fit(X_Train, np.ravel(y_Train))
        pred = Model.predict(X_Test)  

        y_GT.append(y_Test.iloc[0,0])
        y_PT.append(pred[0]) 
 
        abserror.append(np.abs( (y_Test.iloc[0,0] - pred[0])/ y_Test.iloc[0,0] ))


    # Calculating Metrics
    MAPE = 100 * np.mean(abserror)
    # print("Calculated MAPE : ", MAPE )
    # print("Calculated MAPE_func : ", MAPE_func(y_GT,y_PT))
    print(" sklearm MAPE : " , 100 * mape(y_GT,y_PT))
    print(" sklearm MAE : " , mean_absolute_error(y_GT,y_PT))
    print(" sklearm MSE : " , mean_squared_error(y_GT,y_PT))


For :  Random_Forrest_Regression
 rogress : 1/48Progress : 2/48Progress : 3/48Progress : 4/48Progress : 5/48Progress : 6/48Progress : 7/48Progress : 8/48Progress : 9/48Progress : 10/48Progress : 11/48Progress : 12/48Progress : 13/48Progress : 14/48Progress : 15/48Progress : 16/48Progress : 17/48Progress : 18/48Progress : 19/48Progress : 20/48Progress : 21/48Progress : 22/48Progress : 23/48Progress : 24/48Progress : 25/48Progress : 26/48Progress : 27/48Progress : 28/48Progress : 29/48Progress : 30/48Progress : 31/48Progress : 32/48Progress : 33/48Progress : 34/48Progress : 35/48Progress : 36/48Progress : 37/48Progress : 38/48Progress : 39/48Progress : 40/48Progress : 41/48Progress : 42/48Progress : 43/48Progress : 44/48Progress : 45/48Progress : 46/48Progress : 47/48Progress : 48/48

TypeError: 'numpy.float64' object is not callable