In [1]:
from utils import * 

utils.py loaded


## for relu as activation funtion

### Learning y and var

In [2]:
output_2_fvc = model_run(file_name = 'FVC', num_epochs= 500, hidden_sizes =  [50,10], output_size = 2)

Epoch [1/500], Train Loss: 4.8063, Val Loss: 3.9391
Epoch [100/500], Train Loss: -0.2833, Val Loss: 15.1438
Epoch [200/500], Train Loss: -0.6941, Val Loss: 0.1997
Epoch [300/500], Train Loss: -0.5084, Val Loss: -0.1482
Epoch [400/500], Train Loss: -1.0380, Val Loss: 2.8335
Epoch [500/500], Train Loss: -1.6059, Val Loss: 8.3274
MAPE test:  5.822160339355468


In [3]:
output_2_fvc 

(tensor([[3.1577],
         [3.0649],
         [3.0660],
         [3.5160],
         [3.3191]], grad_fn=<ReshapeAliasBackward0>),
 tensor([[0.0206],
         [0.0260],
         [0.0344],
         [0.0166],
         [0.0212]], grad_fn=<ExpBackward0>))

In [5]:
output_2_fev1 = model_run(file_name = 'FEV1', num_epochs= 500, hidden_sizes =  [50,10], output_size = 2)

Epoch [1/500], Train Loss: 3.6416, Val Loss: 2.8251
Epoch [100/500], Train Loss: -0.0989, Val Loss: 0.1270
Epoch [200/500], Train Loss: -0.2612, Val Loss: 0.0592
Epoch [300/500], Train Loss: -0.3856, Val Loss: 0.0711
Epoch [400/500], Train Loss: -0.1991, Val Loss: -0.0319
Epoch [500/500], Train Loss: -0.1635, Val Loss: 0.3311
MAPE test:  8.743933010101319


In [6]:
output_2_fev1

(tensor([[2.6659],
         [2.7566],
         [3.1802],
         [3.3837],
         [3.2814]], grad_fn=<ReshapeAliasBackward0>),
 tensor([[0.0691],
         [0.0550],
         [0.0106],
         [0.0042],
         [0.0175]], grad_fn=<ExpBackward0>))

### Learning y

In [7]:
output_1_fvc = model_run(file_name = 'FVC', num_epochs= 500, hidden_sizes =  [50,10], output_size = 1)

Epoch [1/500], Train Loss: 8.3993, Val Loss: 6.4152
Epoch [100/500], Train Loss: 0.0608, Val Loss: 0.1169
Epoch [200/500], Train Loss: 0.0456, Val Loss: 0.0713
Epoch [300/500], Train Loss: 0.0639, Val Loss: 0.1187
Epoch [400/500], Train Loss: 0.0296, Val Loss: 0.0501
Epoch [500/500], Train Loss: 0.0121, Val Loss: 0.0578
MAPE test:  7.843387603759766


In [8]:
output_1_fvc

tensor([[2.8671],
        [3.2058],
        [3.3606],
        [3.3911],
        [3.2314]], grad_fn=<ReshapeAliasBackward0>)

In [9]:
output_1_fev1 = model_run(file_name = 'FEV1', num_epochs= 500, hidden_sizes =  [50,10], output_size = 1)

Epoch [1/500], Train Loss: 5.1707, Val Loss: 3.9330
Epoch [100/500], Train Loss: 0.0143, Val Loss: 0.0693
Epoch [200/500], Train Loss: 0.0115, Val Loss: 0.1103
Epoch [300/500], Train Loss: 0.0049, Val Loss: 0.1963
Epoch [400/500], Train Loss: 0.0038, Val Loss: 0.1802
Epoch [500/500], Train Loss: 0.0031, Val Loss: 0.1809
MAPE test:  7.96909236907959


In [10]:
output_1_fev1

tensor([[2.6579],
        [2.4321],
        [3.0536],
        [3.3141],
        [3.1089]], grad_fn=<ReshapeAliasBackward0>)

## for sin as activation function

### Learning y and var

In [2]:
output_2_fvc = model_run(file_name = 'FVC', num_epochs= 500, hidden_sizes =  [50,10], output_size = 2, activation='sin')

Epoch [1/500], Train Loss: 3.8592, Val Loss: 3.1031
Epoch [100/500], Train Loss: 0.0689, Val Loss: 0.3457
Epoch [200/500], Train Loss: -0.2123, Val Loss: 1.1997
Epoch [300/500], Train Loss: -0.1979, Val Loss: 2.1635
Epoch [400/500], Train Loss: -0.4579, Val Loss: 0.4226
Epoch [500/500], Train Loss: -0.3834, Val Loss: 1.5070
MAPE test:  4.2397887229919435


In [3]:
output_2_fvc 

(tensor([[3.1020],
         [3.1608],
         [3.1676],
         [3.2778],
         [3.2552]], grad_fn=<ReshapeAliasBackward0>),
 tensor([[0.0316],
         [0.0114],
         [0.0374],
         [0.0382],
         [0.0197]], grad_fn=<ExpBackward0>))

In [4]:
output_2_fev1 = model_run(file_name = 'FEV1', num_epochs= 500, hidden_sizes =  [50,10], output_size = 2,activation='sin')

Epoch [1/500], Train Loss: 3.0828, Val Loss: 1.8302
Epoch [100/500], Train Loss: -0.4349, Val Loss: 1.1484
Epoch [200/500], Train Loss: -0.7407, Val Loss: 1.0484
Epoch [300/500], Train Loss: -0.4894, Val Loss: 1.1803
Epoch [400/500], Train Loss: -0.5895, Val Loss: 0.5052
Epoch [500/500], Train Loss: -0.3552, Val Loss: 0.2533
MAPE test:  5.187931060791016


In [5]:
output_2_fev1

(tensor([[2.5747],
         [2.7170],
         [3.1556],
         [3.0456],
         [3.0695]], grad_fn=<ReshapeAliasBackward0>),
 tensor([[0.3393],
         [0.0692],
         [0.0408],
         [0.1139],
         [0.0175]], grad_fn=<ExpBackward0>))

### Learning y

In [7]:
output_1_fvc = model_run(file_name = 'FVC', num_epochs= 500, hidden_sizes =  [50,10], output_size = 1, activation='sin')

Epoch [1/500], Train Loss: 6.2383, Val Loss: 6.5401
Epoch [100/500], Train Loss: 0.0696, Val Loss: 0.0360
Epoch [200/500], Train Loss: 0.0525, Val Loss: 0.2892
Epoch [300/500], Train Loss: 0.0281, Val Loss: 0.3378
Epoch [400/500], Train Loss: 0.0808, Val Loss: 0.3892
Epoch [500/500], Train Loss: 0.0041, Val Loss: 1.4983
MAPE test:  9.28577823638916


In [8]:
output_1_fvc

tensor([[2.7799],
        [3.0413],
        [3.4141],
        [3.4864],
        [3.2463]], grad_fn=<ReshapeAliasBackward0>)

In [9]:
output_1_fev1 = model_run(file_name = 'FEV1', num_epochs= 500, hidden_sizes =  [50,10], output_size = 1, activation='sin')

Epoch [1/500], Train Loss: 3.0428, Val Loss: 0.5114
Epoch [100/500], Train Loss: 0.0840, Val Loss: 0.0734
Epoch [200/500], Train Loss: 0.0020, Val Loss: 0.0914
Epoch [300/500], Train Loss: 0.0124, Val Loss: 0.0906
Epoch [400/500], Train Loss: 0.0067, Val Loss: 0.0471
Epoch [500/500], Train Loss: 0.0223, Val Loss: 0.0605
MAPE test:  4.7412032127380375


In [10]:
output_1_fev1

tensor([[3.1537],
        [2.8262],
        [2.8953],
        [3.0717],
        [2.9483]], grad_fn=<ReshapeAliasBackward0>)

## Implementing Regressor models with LOOCV

In [ ]:
# for FVC
y_pred_rf = model_regressor(file_name= 'FVC') # default is random forest regression
y_pred_xgb = model_regressor(file_name= 'FVC', regressor_type='XGB')
y_pred_svr = model_regressor(file_name= 'FVC', regressor_type='SVR')

for FVC Overall MPE is = 6.048729090522369
for FVC Overall MPE is = 6.772241273401555
for FVC Overall MPE is = 6.613657490460166


In [ ]:
# for FEV1
y_pred_rf = model_regressor(file_name= 'FEV1') # default is random forest regression
y_pred_xgb = model_regressor(file_name= 'FEV1', regressor_type='XGB')
y_pred_svr = model_regressor(file_name= 'FEV1', regressor_type='SVR')

for FEV1 Overall MPE is = 6.216138273184996
for FEV1 Overall MPE is = 6.3160158903547226
for FEV1 Overall MPE is = 6.80575317785154


### Hyper parameter tuning

In [22]:
config = {
    "hidden_size": tune.choice([[50,10] ,[60,30,5], [75,35,15,5],[128,80,50,30,16]]),
    'lr':tune.choice([0.01, 0.001]),
    "num_epochs": tune.choice([2000])
}

In [2]:
best_config_fvc_out2 = {'hidden_size': [75, 35, 15, 5], 'lr': 0.001, 'num_epochs': 500}
best_config_fev1_out2 = {'hidden_size': [75, 35, 15, 5], 'lr': 0.01, 'num_epochs': 500}
best_config_fvc_out1 = {'hidden_size': [60, 30, 5], 'lr': 0.01, 'num_epochs': 500}        
best_config_fev1_out1 = {'hidden_size': [128, 80, 50, 30, 16], 'lr': 0.001, 'num_epochs': 500}

In [16]:
output_2_fvc = model_run(file_name = 'FVC', num_epochs= best_config_fvc_out2['num_epochs'], hidden_sizes =  best_config_fvc_out2['hidden_size'], output_size = 2, lr = best_config_fvc_out2['lr'])

Epoch [1/500], Train Loss: 7.5943, Val Loss: 8.1030
Epoch [100/500], Train Loss: -0.0895, Val Loss: 4.3815
Epoch [200/500], Train Loss: -0.1199, Val Loss: 6.2287
Epoch [300/500], Train Loss: -0.1957, Val Loss: 8.5090
Epoch [400/500], Train Loss: -0.1763, Val Loss: 15.6482
Epoch [500/500], Train Loss: -0.2335, Val Loss: 14.4548
MAPE test:  7.058881950378418


In [13]:
output_2_fev1 = model_run(file_name = 'FEV1', num_epochs= best_config_fev1_out2['num_epochs'], hidden_sizes =  best_config_fev1_out2['hidden_size'], output_size = 2, lr = best_config_fev1_out2['lr'])

Epoch [1/500], Train Loss: 4.1476, Val Loss: 2.6850
Epoch [100/500], Train Loss: 0.0832, Val Loss: 0.2637
Epoch [200/500], Train Loss: 0.0672, Val Loss: 0.1609
Epoch [300/500], Train Loss: -0.0993, Val Loss: 0.2762
Epoch [400/500], Train Loss: -0.2233, Val Loss: 0.6341
Epoch [500/500], Train Loss: -0.2244, Val Loss: 0.3012
MAPE test:  6.837859439849853


In [17]:
output_1_fvc = model_run(file_name = 'FVC', num_epochs= best_config_fvc_out1['num_epochs'], hidden_sizes =  best_config_fvc_out1['hidden_size'], output_size = 1, lr = best_config_fvc_out1['lr'])

Epoch [1/500], Train Loss: 8.1137, Val Loss: 5.2728
Epoch [100/500], Train Loss: 0.0467, Val Loss: 0.0939
Epoch [200/500], Train Loss: 0.0421, Val Loss: 0.0812
Epoch [300/500], Train Loss: 0.0398, Val Loss: 0.1245
Epoch [400/500], Train Loss: 0.0341, Val Loss: 0.1738
Epoch [500/500], Train Loss: 0.0169, Val Loss: 0.0595
MAPE test:  8.42601375579834


In [3]:
output_1_fev1 = model_run(file_name = 'FEV1', num_epochs= best_config_fev1_out1['num_epochs'], hidden_sizes =  best_config_fev1_out1['hidden_size'], output_size = 1, lr = best_config_fev1_out1['lr'])

Epoch [1/500], Train Loss: 7.6587, Val Loss: 7.7153
Epoch [100/500], Train Loss: 0.0245, Val Loss: 0.0559
Epoch [200/500], Train Loss: 0.0109, Val Loss: 0.0787
Epoch [300/500], Train Loss: 0.0098, Val Loss: 0.0836
Epoch [400/500], Train Loss: 0.0083, Val Loss: 0.1129
Epoch [500/500], Train Loss: 0.0032, Val Loss: 0.1093
MAPE test:  9.896806907653808


Summary 


In [ ]:
# fvc output 2
# MAPE test:  5.872068405151367
# tune:
# MAPE test:  5.188878536224365


# fev1 output 2
# MAPE test:  10.863091468811035
# tune :
# MAPE test:  10.298738479614258


# fvc output 1
# MAPE test:  8.039169311523438
# tune:
# MAPE test:  5.899529457092285


# fev1 output 1
# MAPE test:  9.542654991149902
# tune:
# MAPE test:  9.465457916259766

In [ ]:
analysis_fvc_out1 = raytune_fun(output_size = 1, file_name='FVC') 

In [ ]:
best_config_fvc = analysis_fvc_out1.get_best_config(metric="val_loss", mode="min")
print("Best config:", best_config_fvc)

In [4]:
ray.shutdown()
ray.init()
analysis_fvc = tune.run( train_mlp_output_1,
            config=config,
            num_samples=10,
            progress_reporter=tune.CLIReporter()
        ) 

2023-05-03 23:32:32,985	INFO tune.py:945 -- Total run time: 119.70 seconds (119.46 seconds for the tuning loop).


== Status ==
Current time: 2023-05-03 23:32:32 (running for 00:01:59.55)
Using FIFO scheduling algorithm.
Logical resource usage: 0/8 CPUs, 0/1 GPUs
Result logdir: C:\Users\HP\ray_results\train_mlp_output_1_2023-05-03_23-30-33
Number of trials: 10/10 (10 TERMINATED)
+--------------------------------+------------+-----------------+-----------------+--------+--------+------------------+------------+
| Trial name                     | status     | loc             | hidden_size     |     lr |   iter |   total time (s) |   val_loss |
|--------------------------------+------------+-----------------+-----------------+--------+--------+------------------+------------|
| train_mlp_output_1_6614e_00000 | TERMINATED | 127.0.0.1:21600 | [75, 35, 15, 5] | 0.01   |      1 |        0.512657  |    11.1893 |
| train_mlp_output_1_6614e_00001 | TERMINATED | 127.0.0.1:14260 | [75, 35, 15, 5] | 0.01   |      1 |        0.0180161 |    11.1893 |
| train_mlp_output_1_6614e_00002 | TERMINATED | 127.0.0.1:1924 

In [6]:
best_config_fvc = analysis_fvc.get_best_config(metric="val_loss", mode="min")
print("Best config:", best_config_fvc)

Best config: {'hidden_size': [60, 30, 5], 'lr': 0.01}


In [6]:
import torch

In [7]:
random_seed = 1
torch.manual_seed(random_seed)
print(torch.rand(1,3))

print(torch.rand(1,3))

tensor([[0.7576, 0.2793, 0.4031]])
tensor([[0.7347, 0.0293, 0.7999]])


In [58]:
random_seed = 1
torch.manual_seed(random_seed)
print(torch.rand(1,3))
torch.manual_seed(random_seed)
print(torch.rand(1,3))

tensor([[0.7576, 0.2793, 0.4031]])
tensor([[0.7576, 0.2793, 0.4031]])


In [47]:
torch.rand(1,3)

tensor([[0.4550, 0.5725, 0.4980]])

In [51]:
torch.manual_seed(random_seed)
torch.rand(1,3)

tensor([[0.7576, 0.2793, 0.4031]])